spring.application.name=redpanda-demo
server.port=8081

# 사용자 포트 포워딩 설정 반영 (30092, 30093, 30094)
spring.kafka.bootstrap-servers=localhost:30092,localhost:30093,localhost:30094
spring.kafka.consumer.group-id=redpanda-group
spring.kafka.consumer.auto-offset-reset=earliest

# Jenkins Configuration
jenkins.url=http://localhost:8080
jenkins.username=admin
jenkins.token=admin
jenkins.job.name=demo-pipeline
