replicaCount: 3

image:
  registry: docker.io
  repository: rabbitmq
  tag: 3.13-management
  pullPolicy: IfNotPresent

auth:
  username: user
  password: password
  erlangCookie: secretcookie

metrics:
  enabled: true
  plugins: "rabbitmq_prometheus"
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus

extraPlugins: "rabbitmq_stream"

service:
  type: NodePort
  nodePorts:
    amqp: 30672
    manager: 31672
    stream: 30552
  extraPorts:
  - name: stream
    port: 5552
    targetPort: stream
    protocol: TCP

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi