replicaCount: 3

image:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: latest
  pullPolicy: IfNotPresent

auth:
  username: user
  password: password
  erlangCookie: secretcookie

metrics:
  enabled: true
  plugins: "rabbitmq_prometheus"
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus

service:
  type: NodePort
  nodePorts:
    amqp: 30672
    manager: 31672

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi