server.port=8081
spring.application.name=redpanda-demo

# Kafka (Redpanda) Connection - NodePort 사용
spring.kafka.bootstrap-servers=localhost:30092,localhost:30093,localhost:30094
spring.kafka.consumer.group-id=redpanda-group
spring.kafka.consumer.auto-offset-reset=earliest

# Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer