clusters:
  - name: "redpanda-cluster"
    bootstrapBrokers: "redpanda.redpanda.svc.cluster.local:9093"
    groupWhitelist:
      - ".*" # 모든 컨슈머 그룹 감시
    topicWhitelist:
      - ".*" # 모든 토픽 감시

serviceMonitor:
  enabled: true
  interval: 30s
  labels:
    release: prometheus # 프로메테우스가 찾을 수 있도록 라벨 지정

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
